/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;



import Controlador.Controlador_FRM_MantenimientoUsuarios;
import Modelo.ArchivoUsuario;

/**
 *
 * @author altna
 */
public class FRM_MantenimientoUsuario extends javax.swing.JFrame 
{
     
    public Controlador_FRM_MantenimientoUsuarios controlador;
    ArchivoUsuario archivo;
    
    public FRM_MantenimientoUsuario() 
    {
        initComponents();
        setVisible(false);
        controlador= new Controlador_FRM_MantenimientoUsuarios(this);
        gUI_Botones1.agregarEventos(controlador);
        estadoInicial();
        archivo=new ArchivoUsuario();
    }
    public String[] devolverInformacion()
    {
        return this.gUI_InformacionUsuario1.devolverInformacion();
    }
    public String devolverNombreUsuario()
    {
        return this.gUI_InformacionUsuario1.devolverNombreUsuario();
    
    }

    public void mostrarInformacion(String arreglo[])
    {
        this.gUI_InformacionUsuario1.mostrarInformacion(arreglo);
    }
    
   public void posicionInicial()
    {
        estadoInicial();
        limpiarCampos();
    }
    public void estadoInicial()
    {
        this.gUI_Botones1.estadoInicial();
        this.gUI_InformacionUsuario1.pantallaInicial();
    }
    public void limpiarCampos()
    {
      this.gUI_InformacionUsuario1.limpiarCampos();
    }
    public void habilirAgregar()
    {
      this.gUI_Botones1.habilitarAgregar();
      this.gUI_InformacionUsuario1.habilitarEspacios();
    }
    public void habilirModificar()
    {
        this.gUI_Botones1.habilitarModificar();
        this.gUI_InformacionUsuario1.habilitarEspacios();
    }
    public void habilirEliminar()
    {
        this.gUI_Botones1.habilitarEliminar();
    }
     public void desabilirAgregar()
    {
        this.gUI_Botones1.desabilirAgregar();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_InformacionUsuario1 = new Vista.GUI_InformacionUsuario();
        gUI_Botones1 = new Vista.GUI_Botones();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(gUI_InformacionUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gUI_InformacionUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        archivo.devolverInformacionDeUsuario();
        archivo.crearArchivoUsuario();
        controlador.guardarArchivos();
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_InformacionUsuario gUI_InformacionUsuario1;
    // End of variables declaration//GEN-END:variables
}
