/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_MantenimientoEstudiantes;
import Modelo.ArchivoEstudiantes;
import javax.swing.JOptionPane;

/**
 *
 * @author tecnologiamultimedia
 */
public class FRM_MantenimientoEstudiantes extends javax.swing.JFrame {

    public Controlador_FRM_MantenimientoEstudiantes controlador_FRM_MantenimientoEstudiantes;
    ArchivoEstudiantes archivo;
    
    public FRM_MantenimientoEstudiantes() {
        initComponents();
        setVisible(false);
        controlador_FRM_MantenimientoEstudiantes=new Controlador_FRM_MantenimientoEstudiantes(this);
        gUI_Botones1.agregarEventos(controlador_FRM_MantenimientoEstudiantes);
        archivo=new ArchivoEstudiantes();
    }
    public String[] devolverInformacion()
    {
        return this.gUI_InformacionEstudiantes1.devolverInformacion();
    }
    public String devolverCedula()
    {
        return this.gUI_InformacionEstudiantes1.devolverCedula();
    
    }

   public void mostrarInformacion(String arreglo[])
    {
        this.gUI_InformacionEstudiantes1.mostrarInformacion(arreglo);
    }
    
   public void posicionInicial()
    {
        estadoInicial();
        limpiarCampos();
    }
    public void estadoInicial()
    {
        this.gUI_Botones1.estadoInicial();
        this.gUI_InformacionEstudiantes1.pantallaInicial();
    }
    public void limpiarCampos()
    {
      this.gUI_InformacionEstudiantes1.limpiarCampos();
    }
    public void habilitarOpciones()
    {
        this.gUI_Botones1.habilitarOpciones();
        this.gUI_InformacionEstudiantes1.habilitarOpciones();
    }
    public void habilirAgregar()
    {
      this.gUI_Botones1.habilitarAgregar();
      this.gUI_InformacionEstudiantes1.habilitarEspacios();
    }
    public void mostrarMensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null, mensaje);
    }
    public void limpiarInterfaz()
    {
        this.gUI_InformacionEstudiantes1.limpiarInterfaz();
    }
    public void deshabilitarCedula()
    {
        this.gUI_InformacionEstudiantes1.deshabilitarCedula();
    }
    public void habilirModificar()
    {
        this.gUI_Botones1.habilitarModificar();
        this.gUI_InformacionEstudiantes1.habilitarEspacios();
    }
    public void habilirEliminar()
    {
        this.gUI_Botones1.habilitarEliminar();
    }
     public void desabilirAgregar()
    {
        this.gUI_Botones1.desabilirAgregar();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_InformacionEstudiantes1 = new Vista.GUI_InformacionEstudiantes();
        gUI_InformacionEstudiantes2 = new Vista.GUI_InformacionEstudiantes();
        gUI_Botones1 = new Vista.GUI_Botones();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gUI_InformacionEstudiantes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gUI_InformacionEstudiantes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gUI_InformacionEstudiantes1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gUI_InformacionEstudiantes1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_gUI_InformacionEstudiantes1KeyTyped

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
      archivo.devolverInformacionDeEstudiantes();
     archivo.crearArchivoEstudiantes();
      controlador_FRM_MantenimientoEstudiantes.guardarArchivos();
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_InformacionEstudiantes gUI_InformacionEstudiantes1;
    private Vista.GUI_InformacionEstudiantes gUI_InformacionEstudiantes2;
    // End of variables declaration//GEN-END:variables
}
