/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_MantenimientoCursos;
import Modelo.ArchivoCursos;
import javax.swing.JOptionPane;

/**
 *
 * @author tecnologiamultimedia
 */
public class FRM_MantenimientoCursos extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MantenimientoCursos
     */
    public Controlador_FRM_MantenimientoCursos controlador;
    ArchivoCursos archivo;
    
    public FRM_MantenimientoCursos() {
        initComponents();
        controlador = new Controlador_FRM_MantenimientoCursos(this);
        this.gUI_Botones1.agregarEventos(controlador);
        archivo=new ArchivoCursos();
    }
    public String[] devolverInformacion()
    {
        return this.gUI_InformacionCursos1.devolverInformacion();
    }
    public String devolverSigla()
    {
        return this.gUI_InformacionCursos1.devolverSigla();
    }
    public void mostrarInformacion(String arreglo[])
    {
        this.gUI_InformacionCursos1.mostrarInformacion(arreglo);
    }
    public void deshabilitarSigla()
    {
        this.gUI_InformacionCursos1.deshabilitarSigla();
    }
    public void mostrarMensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null, mensaje);
    }
    public void estadoInicial()
    {
        this.gUI_Botones1.estadoInicial();
        this.gUI_InformacionCursos1.pantallaInicial();
    }
    public void habilitarOpciones()
    {
        this.gUI_Botones1.habilitarOpciones();
        this.gUI_InformacionCursos1.habilitarOpciones();
    }
    public void limpiarInterfaz()
    {
        this.gUI_InformacionCursos1.limpiarInterfaz();
    }
    public void limpiarCampos()
    {
       this.gUI_InformacionCursos1.limpiarCampos();
    }
    public void habilitarAgregar()
    {
        this.gUI_Botones1.habilitarAgregar();
        this.gUI_InformacionCursos1.habilitarEspacios();
    }
    public void habilitarModificar()
    {
        this.gUI_Botones1.habilitarModificar();
        this.gUI_InformacionCursos1.habilitarEspacios();
    }
    public void habilirEliminar()
    {
        this.gUI_Botones1.habilitarEliminar();
    }
    public void deshabilitarAgregar()
    {
        this.gUI_Botones1.desabilirAgregar();
    }
    public void posicionInicial()
    {
        limpiarCampos();
        estadoInicial();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_InformacionCursos1 = new Vista.GUI_InformacionCursos();
        gUI_Botones1 = new Vista.GUI_Botones();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gUI_InformacionCursos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gUI_InformacionCursos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
      archivo.devolverInformacionDeCursos();
      archivo.crearArchivoCursos();
      controlador.guardarArchivos();
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_InformacionCursos gUI_InformacionCursos1;
    // End of variables declaration//GEN-END:variables
}
